Repository openshift/sriov-cni, pull requests merged in 2023-09, with the labels that each got.

#83 Rename downstream Dockerfile + bump
  Dockerfile.rhel
  cmd/sriov/main.go
  pkg/config/config.go
  pkg/sriov/sriov.go
  pkg/sriov/sriov_test.go
  pkg/types/types.go
  pkg/utils/utils.go
  pkg/utils/utils_test.go
Labels: lgtm, approved

#85 OCPBUGS-17799: Rename and bump to rhel9
  .ci-operator.yaml
  Dockerfile.rhel
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-critical, jira/valid-reference

#81 OCPBUGS-17396: [release-4.12] Retry on driver error
  cmd/sriov/main.go
  pkg/sriov/sriov.go
  pkg/sriov/sriov_suite_test.go
  pkg/sriov/sriov_test.go
  pkg/utils/testing.go
  pkg/utils/utils.go
  pkg/utils/utils_test.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-important, jira/valid-reference
