Repository openshift/sriov-cni, pull requests merged in 2024-05, with the labels that each got.

#105 add Snyk
  .snyk
Labels: lgtm, approved

#104 OCPBUGS-33799: Merge https://github.com/k8snetworkplumbingwg/sriov-cni:master into master
  go.mod
  go.sum
  images/k8s-v1.10-v1.15/sriov-cni-daemonset.yaml
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/sriov/sriov.go
  pkg/sriov/sriov_test.go
  pkg/types/types.go
  pkg/utils/utils.go
  pkg/utils/utils_test.go
  vendor/golang.org/x/net/html/token.go
  vendor/golang.org/x/sys/unix/aliases.go
  vendor/golang.org/x/sys/unix/syscall_darwin_libSystem.go
  vendor/golang.org/x/sys/unix/syscall_freebsd.go
  vendor/golang.org/x/sys/unix/syscall_linux.go
  vendor/golang.org/x/sys/unix/zsyscall_linux.go
  vendor/golang.org/x/sys/unix/ztypes_linux.go
  vendor/modules.txt
Labels: lgtm, approved, jira/valid-bug, jira/severity-critical, jira/valid-reference

#106 OCPBUGS-34033: [release-4.14] build for RHEL8 and RHEL9
  Dockerfile.rhel
  Makefile
  images/entrypoint.sh
  images/image_test.sh
  images/image_test_rhel.sh
  images/testdata/rhel8-etc-os-release
  images/testdata/rhel9-etc-os-release
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#108 OCPBUGS-34582: Fix cache 4.16
  .snyk
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/sriov/sriov.go
  pkg/sriov/sriov_test.go
  pkg/types/types.go
  pkg/utils/utils.go
  pkg/utils/utils_test.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-critical, jira/valid-reference
